export { Navbar } from './Navbar'
export { Footer } from './Footer'
export { Loader } from './Loader'
export { Services } from './Services'
export { Transactions } from './Transactions'
export { Welcome } from './Welcome'